### ISSUE TITLE
expecting bytes, NoneType found

### ISSUE THREAD

**Issue by DavidPratten** [coleifer/sqlite-vtfunc#11]
Any clues as to what is going on here?

After successful `pip install vtfunc` on Windows 10, Python39 (See comments on  https://github.com/coleifer/sqlite-vtfunc/issues/10 )

Got these errors

>   RegexSearch.register(conn)
>   File "vtfunc.pyx", line 612, in vtfunc.TableFunction.register
>   File "vtfunc.pyx", line 576, in vtfunc._TableFunctionImpl.create_module
> TypeError: expected bytes, NoneType found

when executing sample code from https://github.com/coleifer/sqlite-vtfunc .

```
import re

from vtfunc import TableFunction


class RegexSearch(TableFunction):
    params = ['regex', 'search_string']
    columns = ['match']
    name = 'regex_search'

    def initialize(self, regex=None, search_string=None):
        self._iter = re.finditer(regex, search_string)

    def iterate(self, idx):
        # We do not need `idx`, so just ignore it.
        return (next(self._iter).group(0),)

import sqlite3

conn = sqlite3.connect(':memory:')  # Create an in-memory database.

RegexSearch.register(conn)  # Register our module.

query_params = ('[0-9]+', '123 xxx 456 yyy 789 zzz 0')
cursor = conn.execute('SELECT * FROM regex_search(?, ?);', query_params)
print cursor.fetchall()
```

**Comment by coleifer** [comment]
I'm not sure what to tell you - it's working fine on my machine.
