### ISSUE TITLE
Consider merging this functionality into pysqlite

### ISSUE THREAD

**Issue by phrrngtn** [coleifer/sqlite-vtfunc#12]
Hi,
I found your pysqlite extension hugely useful as I could have a dbapi2 sqlite driver to use with SQLAlchemy and have control over all of the goodies compiled in from the amalgamation. Thanks for that. I find the backup API particularly useful (a common pattern is to do a bunch of stuff in a :memory: database and then back that up to persistent storage if everything goes OK).

What do you think of  merging  the virtual table functionality in this package into pysqlite? I think that would be hugely useful and am quite happy to slog through the details of getting it working but want to check with you first what you think of the idea.

thanks in advance,
pjjH

**Comment by coleifer** [comment]
I'm going to pass for now, thanks for your interest!
