### ISSUE TITLE
Returning anything other than a tuple from iterate() throws unhelpful "OperationalError: SQL logic error"

### ISSUE THREAD

**Issue by simonw** [coleifer/sqlite-vtfunc#5]
I kept getting `OperationalError: SQL logic error` when I tried to run SQL queries against my new table function.

Eventually I realized it was because I was returning a `[]` list from my `iterate()` method. Returning a tuple instead made the error go away.

A few options for improvements here:

* Allow lists in addition to tuples to be returned from `iterate()`
* Improve the error message that is displayed in this case
* Improve the documentation to make it VERY clear that it needs to display tuples (and maybe to ensure that if someone searches for "SQL logic error" they get a clue about this)

I don't have a strong opinion on which of these I prefer - really just wanted to raise this as a minor usability issue.

**Comment by coleifer** [comment]
> Improve the error message that is displayed in this case

Yeah, this is difficult -- the error occurs in what amounts to a C callback. i.e., SQLite itself is calling the `iterate()` method. Let me look at the source for pysqlite and see if I can figure out something better.

I'll take a look at the return value issue as well, cheers.

**Comment by coleifer** [comment]
Well, it looks like pysqlite is just printing the traceback if an error occurs in a callback, so I've updated the module to do the same. I've also added tests for various error conditions (error instantiating, error initializing, error iterating, and error iterating under certain circumstances).

**Comment by coleifer** [comment]
Pushed a new version, 0.3.4, which contains these fixes.
