### ISSUE TITLE
Here's what I've been building

### ISSUE THREAD

**Issue by simonw** [coleifer/sqlite-vtfunc#6]
I want to play with table functions for Datasette plugins. Here's what I've got so far: https://github.com/simonw/datasette-sql-scraper

And here's a live demo: https://datasette-sql-scraper-demo.now.sh/fixtures-fda0fea?sql=select+*+from+scraper%28%22http%3A%2F%2Fwww.example.com%2F%22%29

https://datasette-sql-scraper-demo.now.sh/fixtures-fda0fea?sql=select+*+from+scraper%28%22http%3A%2F%2Fnews.ycombinator.com%2F%22%29+order+by+length%28description%29+desc

Still need to figure out the best way of further developing this. Biggest problem at the moment is that I'm getting `SQL logic error` in many situations e.g. https://datasette-sql-scraper-demo.now.sh/fixtures-fda0fea?sql=select+*+from+scraper%28%22https%3A%2F%2Fsimonwillison.net%2F%22%29 and I don't know the best way to debug why.

**Comment by simonw** [comment]
Plugin documentation is here: http://datasette.readthedocs.io/en/stable/plugins.html

**Comment by coleifer** [comment]
The changes from 92facaf66b879a978a15c1b89ebb66ddcd75b1c6 - which is available as 0.3.4 - should make debugging easier. Unfortunately there's no way to bubble the exception out of the initialize/iterate methods because those are essentially C callbacks that are called internally by SQLite when it's executing the query. The best we can do is to print the traceback (which is incidentally why pysqlite is doing when you have a buggy user-defined function, for example). That should hopefully make debugging easier.

**Comment by coleifer** [comment]
I'm glad you're finding the library cool... I always felt like it was a pretty neat little library, encapsulating the virtual table APIs to the point where they're stupid-simple to implement in Python :)

**Comment by simonw** [comment]
I'd love to see this ship as part of Python sqlite3 - it's SUCH a useful capability, and your API design is really neat.

**Comment by simonw** [comment]
Your traceback fix is exactly what I need:

```
[2018-05-25 10:42:33 -0700] [48919] [INFO] KeepAlive Timeout. Closing connection.
HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "vtfunc.pyx", line 394, in vtfunc.pwFilter
  File "/Users/simonw/Dropbox/Development/datasette/venv/lib/python3.6/site-packages/datasette_sql_scraper/__init__.py", line 25, in iterate
    return next(self._iter).groups()
TypeError: 'list' object is not an iterator
ERROR: conn=<sqlite3.Connection object at 0x109e5b490>, sql = 'select * from scraper("http://simonwillison.net/") order by length(description) desc', params = {}: SQL logic error
```

**Comment by simonw** [comment]
Thanks to that I was able to debug one of the above issues: turns out Cloudflare for simonwillison.net was blocking the Python urllib user-agent. I [turned that off](https://support.cloudflare.com/hc/en-us/articles/200171806-Error-1010-The-owner-of-this-website-has-banned-your-access-based-on-your-browser-s-signature) and this works now:

https://datasette-sql-scraper-demo.now.sh/fixtures-fda0fea?sql=select+*+from+scraper%28%22https%3A%2F%2Fsimonwillison.net%2F%22%29+order+by+length%28href%29+desc

**Comment by simonw** [comment]
This is fun too:

https://datasette-sql-scraper-demo.now.sh/fixtures-fda0fea?sql=select+*+from+%28%0D%0Aselect+1%2C+*+from+scraper%28%22http%3A%2F%2Fwww.example.com%2F%22%29%0D%0A++union%0D%0Aselect+2%2C+*+from+scraper%28%22https%3A%2F%2Fsimonwillison.net%2F%22%29%0D%0A++union%0D%0Aselect+3%2C+*+from+scraper%28%22https%3A%2F%2Fnews.ycombinator.com%2F%22%29%0D%0A%29+order+by+length%28description%29+desc%3B

```
select * from (
select 1, * from scraper("http://www.example.com/")
  union
select 2, * from scraper("https://simonwillison.net/")
  union
select 3, * from scraper("https://news.ycombinator.com/")
) order by length(description) desc;
```
I'm trying to figure out if it's possible to run the `scraper()` function against the results from another table - in SQL-pseudocode something like this (though this is obviously wrong):

```
select scraper(href) where href in ("https://simonwillison.net/", "https://news.ycombinator.com/");
```

**Comment by coleifer** [comment]
Should be:

```python

    def test_split_tbl(self):
        Split.register(self.conn)
        self.execute('create table post (content TEXT);')
        self.execute('insert into post (content) values (?), (?), (?)',
                     ('huey secret post',
                      'mickey message',
                      'zaizee diary'))
        curs = self.execute('SELECT * FROM post, str_split(post.content)')
        results = curs.fetchall()
        self.assertEqual(results, [
            ('huey secret post', 'huey'),
            ('huey secret post', 'secret'),
            ('huey secret post', 'post'),
            ('mickey message', 'mickey'),
            ('mickey message', 'message'),
            ('zaizee diary', 'zaizee'),
            ('zaizee diary', 'diary'),
        ])
```

**Comment by simonw** [comment]
Thanks - I got this to work:
```
select a.href as origin_url, s.href as url_on_page from scraper(a.href) s
join (
  select href from scraper("https://simonwillison.net/")
  where href like "http%" and href not like "%github%" limit 3
) as a
```
https://datasette-sql-scraper-demo.now.sh/fixtures-fda0fea?sql=select+a.href+as+origin_url%2C+s.href+as+url_on_page+from+scraper%28a.href%29+s%0D%0Ajoin+%28%0D%0A++select+href+from+scraper%28%22https%3A%2F%2Fsimonwillison.net%2F%22%29%0D%0A++where+href+like+%22http%25%22+and+href+not+like+%22%25github%25%22+limit+3%0D%0A%29+as+a

**Comment by simonw** [comment]
```
select 1 url
  union all
select * from (values ("https://simonwillison.net/"), ("http://www.example.com/"))
limit 100000 offset 1
```
The `union all / offset 1` trick is needed to give a known alias to the generated column:

| url |
|----|
| https://simonwillison.net/  |
| http://www.example.com/  |

https://datasette-sql-scraper-demo.now.sh/fixtures-fda0fea?sql=select+1+url%0D%0A++union+all%0D%0Aselect+*+from+%28values+%28%22https%3A%2F%2Fsimonwillison.net%2F%22%29%2C+%28%22http%3A%2F%2Fwww.example.com%2F%22%29%29%0D%0Alimit+100000+offset+1%0D%0A

Now I can use the above trick to run `scraper()` against both of those URLs: https://datasette-sql-scraper-demo.now.sh/fixtures-fda0fea?sql=select+a.url%2C+s.href%2C+s.description+from+scraper%28a.url%29+s%0D%0Ajoin+%28%0D%0A++select+1+url%0D%0A++++union+all%0D%0A++select+*+from+%28values+%28%22https%3A%2F%2Fsimonwillison.net%2F%22%29%2C+%28%22http%3A%2F%2Fwww.example.com%2F%22%29%29%0D%0A++limit+100000+offset+1%0D%0A%29+as+a%0D%0A

```
select a.url, s.href, s.description from scraper(a.url) s
join (
  select 1 url
    union all
  select * from (values ("https://simonwillison.net/"), ("http://www.example.com/"))
  limit 100000 offset 1
) as a

```

**Comment by coleifer** [comment]
you could probably do a recursive scrape with something like this (untested):

```sql
with recursive url_list(href, desc) as (
    select url, description from scraper('http://base-url.com/')
union all
    select url, description from scraper(url_list.href)
)
select * from url_list
limit 1000;
```
