### ISSUE TITLE
Document the minimum required version of SQLite

### ISSUE THREAD

**Issue by simonw** [coleifer/sqlite-vtfunc#7]
This module seems to work with SQLite 3.23.1 ( https://datasette-sql-scraper-demo.now.sh/-/versions ) but throws errors when run against `3.8.7.1`:

https://datasette-sql-scraper-broken-on-older-version.now.sh/fixtures-fda0fea?sql=select+*+from+scraper%28%22http%3A%2F%2Fwww.example.com%2F%22%29

`Invalid SQL: near "(": syntax error`

Version shown here: https://datasette-sql-scraper-broken-on-older-version.now.sh/-/versions

It would be useful to document the minimum required version of SQLite for this to work.

**Comment by coleifer** [comment]
Yeah it requires 3.9. I'll add that.

**Comment by coleifer** [comment]
ca6a02264fd0313a0436f546c7f6f82097bed564
