### ISSUE TITLE
is there any way to create a table-valued function return dynamic columns?

### ISSUE THREAD

**Issue by kaixinbuyu** [coleifer/sqlite-vtfunc#9]
Currently a virtual table must have fixed columns.
Is there any way,to create one table-valued function return dynamic columns associated with input parameters?

eg:
1.create one table-valued function :
**web_crawler**(url,extractor) 
this function can automatic extract different columns fields by the page type.

2.when query:
Can table-valued function return different columns by inputed parameters?

select * from **web_crawler**(url='www.a-blog.com/list.html',extractor='blog-extractor');
return 4 fields:
<url,title,content,comment>

select * from **web_crawler**(url='www.a-online-shop.com/list.html',extractor='shop-extractor');
return 5 fields:
<url,product-name,price,product-image,description>

select * from **web_crawler**(url='www.a-online-news.com/list.html',extractor='news-extractor');
return 4 fields:
<url,news-title,publish-date,news-content>

instead of create many virtual tables for each extractor?

**Comment by coleifer** [comment]
Sorry brobeans, but that's not how SQL works. You'll have to dynamically register a new table for each set of columns.

I'd suggest -- if you're hell-bent on doing something like this -- that you dump the dynamic parts into a JSON column, since sqlite has decent json support.
